name: Publish to npm

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Configure NPM Auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc
          ls -al
          cat ./.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Bump version
        run: git config --global user.name "bluetti[bot]" && git config --global user.email "bluettibot@bluetti.com" && git pull origin main && npm version patch

      - name: Push changes
        run: |
          git push origin main --follow-tags

      - name: Publish to npm
        run: |
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}